### PR TITLE
Feature/book recommendation ml model deployment

### PR DESCRIPTION
**Pull request by joembarron**
PR for merging Book Rating Predictions notebook into the main branch.

### CODE REVIEW

**Review by BrianMcDowell — DISMISSED** [review]
Looks good.

**Comment by joembarron** [comment]
@BrianMcDowell Can you review this PR?

**Review by BrianMcDowell — APPROVED** [review]
Looks good.

**Review by GriffinBalducci — APPROVED** [review]
Reviewed

**Pull request merged**
